[package]
name = "obs_websocket"
version = "0.1.0"
authors = ["Brian Spit <brian@mythenatic.com>"]
edition = "2018"

[dependencies]
websocket = "0.22.4"
serde_json = "1.0.39"
base64 = "0.10.1"
rust-crypto = "0.2.36"